services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medicine-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medicine-backend
    ports:
      - "3001:3001"
    restart: unless-stopped
